apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: grafana
  name: grafana-alerting
spec:
  ports:
  - name: gossip
    port: 9094
    protocol: TCP
    targetPort: gossip-tcp
  selector:
    app.kubernetes.io/name: grafana
  type: ClusterIP
  clusterIP: 'None'