apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: grafana
  name: grafana
spec:
  ports:
  - name: grafana
    port: 80
    protocol: TCP
    targetPort: grafana
  selector:
    app.kubernetes.io/name: grafana
  type: ClusterIP