apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

buildMetadata: [managedByLabel]
namespace: grafana

resources:
  - resources/deployment.yaml
  - resources/pvc.yaml
  - resources/service.yaml

images:
  - name: grafana/grafana
    newTag: &version 10.4.1

configMapGenerator:
  - envs:
      - config/grafana.env
    name: grafana-env

labels:
  - pairs:
      app.kubernetes.io/version: *version
      app.kubernetes.io/name: "grafana"
