apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana
buildMetadata: [managedByLabel]

resources:
  - resources/deployment.yaml
  - resources/service.yaml

images:
  - name: grafana/grafana-image-renderer
    newTag: &version 3.10.1

configMapGenerator:
  - envs:
      - config/grafana-image-renderer.env
    name: grafana-image-renderer-env

labels:
  - pairs:
      app.kubernetes.io/name: grafana-image-renderer
      app.kubernetes.io/version: *version
