apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

buildMetadata: [managedByLabel]
namespace: grafana

resources:
  - service-monitor.yaml

labels:
  - pairs:
      app.kubernetes.io/name: grafana
