apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: grafana
  name: grafana
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: grafana
  namespaceSelector: {}
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana