apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana
buildMetadata: [managedByLabel]

resources:
  - service-monitor.yaml

labels:
  - pairs:
      app.kubernetes.io/name: grafana-image-renderer
