apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: grafana-image-renderer
  name: grafana-image-renderer
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: service
  namespaceSelector: {}
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-image-renderer
