apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: grafana-image-renderer
  name: grafana-image-renderer
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-image-renderer
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana-image-renderer
    spec:
      containers:
      - name: grafana-image-renderer
        image: grafana/grafana-image-renderer:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: grafana-image-renderer-env
        - secretRef:
            name: grafana-image-renderer
            optional: true
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        ports:
        - containerPort: 8081
          name: service
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8081
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "2"
            memory: 1024Mi
          requests:
            cpu: 500m
            memory: 1024Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
