apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: grafana-image-renderer
  name: grafana-image-renderer
spec:
  ports:
  - name: service
    port: 8081
    protocol: TCP
    targetPort: service
  selector:
    app.kubernetes.io/name: grafana-image-renderer
  type: ClusterIP
