apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

buildMetadata: [managedByLabel]
namespace: grafana

resources:
  - ../grafana-ha
  - ../../base/grafana/monitoring
  - ../../base/grafana-image-renderer
  - ../../base/grafana-image-renderer/monitoring
